name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: piber/workflows-config/.github/workflows/semantic-release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
